# Generated by Django 6.0 on 2025-12-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_lead_description_lead_email_lead_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
