# Generated by Django 6.0 on 2025-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Teal CRM', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('base_url', models.URLField(default='http://127.0.0.1:8000')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
