# Generated by Django 6.0 on 2025-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Teal CRM', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AppSettings',
        ),
    ]
