# Generated by Django 6.0 on 2025-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_lead_converted_to_client_lead_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_name',
            field=models.CharField(default='Unnamed Lead', help_text='Display name for the lead (e.g. ACME Website Enquiry)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
